### ISSUE TITLE
Image2Surface only works one time!

### ISSUE THREAD

**Issue by DaveGadgeteer** [hanskellner/Fusion360Image2Surface#7]
Thank you for Image2Surface, it's just what I need.
It worked one time, even though I just dragged an image from Photos onto it, which was likely too many pixels. Fusion got very busy, but after 40 mins it finished, and there was the surface!
I then converted it to Tsplines so I could 3D print it, and that too took a while, but afterward Fusion became unresponsive so that I could not move my view, didn't see the resulting converted surface.
So I figured I'd do it again with smaller demands on it, but I cannot run Image2Surface anymore. The controlling dialog just comes up empty. I tried restarting Fusion, then restarting my Mac, no luck.
When I quit Fusion I got an error message, attached.
Any ideas what to try next to get things working again?
<img width="424" alt="screenshot 2018-11-04 12 53 39" src="https://user-images.githubusercontent.com/3915712/47969945-ac17e080-e033-11e8-9830-9f4339fefd8b.png">

**Comment by hanskellner** [comment]
@DaveGadgeteer I'll take a look at the issue.  I'm wondering if something has been messed up in Fusion's addin install/loading support.  Possibly because Fusion didn't exit cleanly after trying to work with the very large image.

First, with Fusion not running, delete the folder where you installed Image2Surface.  Start Fusion and then display the add-in dialog.  If the Image2Surface addin is listed, right-click (ctrl-click) on the entry and select the remove item.  Exit Fusion.

Now go through the install steps for the Image2Surface addin.  Once installed, see if it loads and runs.  Test with a small image.  Hopefully those steps will work and it again runs for you.  

As for the very large photo, this is going to be a problem with Fusion at this time.  One thing I do with large images is to make a copy of an image.  Then load the copy into an image editing app and scale the image down to a smaller size.  Use this smaller size image when importing into Image2Surface and then Fusion.

**Comment by DaveGadgeteer** [comment]
I haven't had any success. New version of Fusion tonight.
Symptom is still big empty window with no UI except "close" button,
which works.Still see the same complaint when I quit Fusion, can't delete palette.
Must be a clue...Any suggestions?
I can see/edit your source, could do some debugging if you can suggest
what might be useful.
--
  David Gustavson
  dbg@SCIzzL.com



On Sun, Nov 4, 2018, at 5:47 PM, Hans wrote:
> @DaveGadgeteer[1] I'll take a look at the issue.  I'm wondering if
> something has been messed up in Fusion's addin install/loading
> support.  Possibly because Fusion didn't exit cleanly after trying to
> work with the very large image.> First, with Fusion not running, delete the folder where you installed
> Image2Surface.  Start Fusion and then display the add-in dialog.  If
> the Image2Surface addin is listed, right-click (ctrl-click) on the
> entry and select the remove item.  Exit Fusion.> Now go through the install steps for the Image2Surface addin.  Once
> installed, see if it loads and runs.  Test with a small image.
> Hopefully those steps will work and it again runs for you.> As for the very large photo, this is going to be a problem with Fusion
> at this time.  One thing I do with large images is to make a copy of
> an image.  Then load the copy into an image editing app and scale the
> image down to a smaller size.  Use this smaller size image when
> importing into Image2Surface and then Fusion.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/DaveGadgeteer
  2. https://github.com/hanskellner/Fusion360Image2Surface/issues/7#issuecomment-435731414

**Comment by hanskellner** [comment]
@DaveGadgeteer I'm working through various tests to try to find the issue.  So far I haven't been able to reproduce the problem.  A couple of questions:

- Is your Fusion installed through the app store?
- When you delete the addin and run Fusion, do you get any error messages?

Thanks
